source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "trilogy"
gem "puma", ">= 5.0"

# Auth
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.8"

# CORS
gem "rack-cors"

# Pagination
gem "kaminari"

# Authorization
gem "pundit"

# Background jobs
gem "sidekiq"

# PDF generation
gem "prawn"
gem "prawn-table"

# Image processing
gem "image_processing", "~> 1.2"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
